---
- name: Copy 'prometheus-policy'
  copy:
    src: "prometheus-policy.vault"
    dest: "/home/{{ ansible_ssh_user }}/prometheus-policy.vault"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: Write 'prometheus-policy' to Vault # noqa 301
  no_log: yes
  command: "vault policy write prometheus /home/{{ ansible_ssh_user }}/prometheus-policy.vault"
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ vault_root_token }}"

- name: Enable key-value secret engine # noqa 301
  no_log: yes
  shell: vault secrets enable -version=1 kv || true
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ vault_root_token }}"

- name: Store some demo values for 'hello-vault' application # noqa 301
  no_log: yes
  command: |
    vault kv put kv/hello-vault
      url='api.example.com'
      username='admin'
      password='pa$$w0rd'
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ vault_root_token }}"

- name: Copy 'hello-world-vault-policy'
  copy:
    src: "{{ playbook_dir }}/nomad_jobs/hello-world-vault-policy.vault"
    dest: "/home/{{ ansible_ssh_user }}/hello-world-vault-policy.vault"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: Write 'hello-world-vault-policy' to Vault # noqa 301
  no_log: yes
  command: "vault policy write hello-vault /home/{{ ansible_ssh_user }}/hello-world-vault-policy.vault"
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "{{ vault_root_token }}"
